### ISSUE TITLE
DeprecationWarning: the imp module is deprecated in favour of importlib

### ISSUE THREAD

**Issue by Gallaecio** [RDFLib/pyrdfa3#31]
```
[…]/pyRdfa/utils.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import os, os.path, sys, imp, datetime
```
— https://travis-ci.org/scrapinghub/extruct/jobs/594543651

**Comment by iherman** [comment]
Thanks @Gallaecio. Actually, it turns out that the reference to 'imp' was unnecessary, it was not used in the code at all. (Some sort of a leftover, I am not even sure any more why it was there.) So I removed the reference.
