### ISSUE TITLE
Python 3 import error in pyRdfaExtras/__init__.py

### ISSUE THREAD

**Issue by Apteryks** [RDFLib/pyrdfa3#42]
Hi,

This import fallback: https://github.com/RDFLib/pyrdfa3/blob/404bd418575ddcd58a0d5b0fe47b6d9d33ff5ead/pyRdfaExtras/__init__.py#L35 is broken on Python 3.

It should be `from io import StringIO`.

Thanks.

**Comment by iherman** [comment]
I hate the lack of backward incompatibilities of Python 3....

Anyway, I have made the change in https://github.com/RDFLib/pyrdfa3/commit/059471bcb3a7e42d271384374047eb25411f4351

Thanks!

**Comment by iherman** [comment]
Can you close the issue if it is all right now? Thx.

(Any chance you know someone who would be happy taking over the maintenance of this repo?)

**Comment by Apteryks** [comment]
I just tested the latest commit without my local changes, and I still got:
```
RdfaExtras/serializers/prettyXMLserializer_3.py'...
Compiling '/gnu/store/dkai06zawanq3qxv9v9911137f1fd3zz-python-pyrdfa3-3.5.3/lib/python3.9/site-packages/pyRdfaExtras/serializers/prettyXMLserializer_3_2.py'...
*** Sorry: TabError: inconsistent use of tabs and spaces in indentation (prettyXMLserializer_3_2.py, line 219)
Compiling '/gnu/store/dkai06zawanq3qxv9v9911137f1fd3zz-python-pyrdfa3-3.5.3/lib/python3.9/site-packages/pyRdfaExtras/serializers/turtleserializer.py'...
error: in phase 'install': uncaught exception:
%exception #<&invoke-error program: "python" arguments: ("-m" "compileall" "--invalidation-mode=unchecked-hash" "/gnu/store/dkai06zawanq3qxv9v9911137f1fd3zz-python-pyrdfa3-3.5.3") exit-status: 1 term-signal: #f stop-signal: #f>
```
Is this `pyRdfaExtras/serializers/prettyXMLserializer_3_2.py` file even supposed to be installed? I'm on Python 3.9.9.
