### ISSUE TITLE
pyrdfa3 repository vs. rdflib's copy of pyrdfa3

### ISSUE THREAD

**Issue by dbs** [RDFLib/pyrdfa3#9]
Repeating the question I just asked on #rdflib - why is there both a top-level pyrdfa3 repository, and a separate copy of pyrdfa3 under the rdflib repository's plugins/parsers subdirectory?

If rdflib was using git submodules to pull in pyrdfa3, that would make some sense; it would enable us to focus on pyrdfa3 as a separate module and hopefully avoid bugs like #7 where rdflib's setup.py handles the 2to3 conversion, while pyrdfa3's own does not.

As an entirely separate copy, however, the risk is that fixes to one repo won't get into the other. And the repos are in fact slightly out of sync with one another (a couple of lines concerning type checking with isinstance()).

**Comment by iherman** [comment]
Overtaken by events. The latest evolution of RDFLib is to remove the RDFa parser from the core distribution, and this code is meant to be the one used as a plugin.
